### PR TITLE
Add arguments and path, clean up

### PR DESCRIPTION
**Pull request by Cretezy**
Added `{}` argument, with `path`. Also cleaned up some parts of the code (make `final` when can be) and the README (also added undocumented features such as `.` strings).

### CODE REVIEW

**Comment by Skyost** [comment]
@Cretezy Okay so a few points :

1. First, thanks a lot for contributing !
2. You're totally right about the nested strings part.
3. The second commit is also good but I prefer a strong typing in the project (and Dart allows us to do so).
4. Why using a `path` argument with a `getPathFunction` ? It seems a bit duplicate to me as the default `getPathFunction` is exactly `$path/language.json`.
5. One last thing : you've added three transitive dependencies in `example/pubspec.lock` : `petitparser`, `image` and `xml`. Are they needed ?
6. I don't see the matter of putting `final` everywhere. There was a myth at the time of Java where everybody was saying that `final` was faster. It's clearly not the case in Dart 😄 
7. I think named arguments is a better and cleaner option to add arguments.

**Comment by Skyost** [comment]
I've made the following changes : https://github.com/Skyost/EzLocalization/pull/1/commits/1e49dbd9363e4154890eeae2948b62fdddefa812, is it fair to you ?

**Comment by Cretezy** [comment]
For 3, final does do strong typing since you can't redeclare the type.

For 4, it's usually easier to give a path than a function, so support for both is nicer. 

For 5, pub did that on its own. Don't know why. 

For 6, it's usually a best practice since it can lead to fewer bugs from accidentally assigning something.

(on mobile right now, will check again later)

**Comment by Skyost** [comment]
Yeah I understand your point of view. But anyway, I prefer not to make everything `final` and to replace it with the class name. That's a convention I've been using for a while now.

The `path` still seems duplicate to me. Maybe creating a function that allows to create a `getPathFunction` directly from a path ?

**Pull request merged**
